---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: 37.59.48.5:5000/yabsambaye/myweb:10
        imagePullPolicy: Always
        name: myweb
  ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: myweb
